# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  # Provisioning configuration for Ansible.
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
    end
end
