# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :server1 do |server1|
    server1.vm.box = "ubuntu/jammy64"
    server1.vm.network "private_network", ip: "192.168.56.100"
  end
end
